/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog
         * @description Return the full node-type catalog (categories, types, images, sources).
         */
        get: operations["get_catalog_api_v1_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Images
         * @description Host build support, image sources, and the status of each image.
         *
         *     Without ``topology_id``: every image the catalog describes.
         */
        get: operations["list_images_api_v1_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Images
         * @description Start a build job per image (an image already building returns its job).
         */
        post: operations["build_images_api_v1_images_builds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Cancel a queued or running job. Deploys can only be cancelled before the
         *     engine starts creating containers; destroys cannot be cancelled.
         */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Log
         * @description A slice of the job's log. ``done`` turns true once the job has finished
         *     and the slice reaches the end of the log.
         */
        get: operations["get_job_log_api_v1_jobs__job_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_api_v1_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets/{preset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preset */
        get: operations["get_preset_api_v1_presets__preset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets/{preset_id}/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Preset
         * @description Create a new topology from a preset template.
         */
        post: operations["load_preset_api_v1_presets__preset_id__load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{name}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Source
         * @description Fetch a git source's configured ref; the job reports which images changed.
         */
        post: operations["sync_source_api_v1_sources__name__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Labs
         * @description Every lab the engine is running, matched against saved topologies.
         */
        get: operations["labs_api_v1_system_labs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/labs/{lab_hash}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purge Lab
         * @description Remove a lab's containers and networks whatever user prefix they carry.
         */
        post: operations["purge_lab_api_v1_system_labs__lab_hash__purge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Reconcile
         * @description Reset topologies whose lab is gone; report orphans (purge is explicit).
         */
        post: operations["run_reconcile_api_v1_system_reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topologies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topologies */
        get: operations["list_topologies_api_v1_topologies_get"];
        put?: never;
        /** Create Topology */
        post: operations["create_topology_api_v1_topologies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topologies/import-json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Json */
        post: operations["import_json_api_v1_topologies_import_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topologies/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Data
         * @description Validate a topology document without saving it.
         */
        post: operations["validate_data_api_v1_topologies_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topologies/{topology_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topology */
        get: operations["get_topology_api_v1_topologies__topology_id__get"];
        /** Update Topology */
        put: operations["update_topology_api_v1_topologies__topology_id__put"];
        post?: never;
        /** Delete Topology */
        delete: operations["delete_topology_api_v1_topologies__topology_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topologies/{topology_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Context
         * @description Everything about a topology in one response: record + diagnostics, plan, runtime, recent events.
         */
        get: operations["get_context_api_v1_topologies__topology_id__context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topologies/{topology_id}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deploy
         * @description Start a deploy job. Poll ``/runtime`` (or ``/jobs/{id}``) for progress.
         */
        post: operations["deploy_api_v1_topologies__topology_id__deploy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topologies/{topology_id}/destroy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Destroy */
        post: operations["destroy_api_v1_topologies__topology_id__destroy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topologies/{topology_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_api_v1_topologies__topology_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topologies/{topology_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Topology
         * @description Portable representations of the lab: JSON spec, Kathara folder, or ContainerLab topology (zips).
         */
        get: operations["export_topology_api_v1_topologies__topology_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topologies/{topology_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topology Jobs */
        get: operations["list_topology_jobs_api_v1_topologies__topology_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topologies/{topology_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan
         * @description The engine-agnostic lab plan: what deploy would instantiate.
         */
        get: operations["get_plan_api_v1_topologies__topology_id__plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topologies/{topology_id}/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Runtime
         * @description Deployment status, the active job (with steps), and per-node state in one call.
         */
        get: operations["get_runtime_api_v1_topologies__topology_id__runtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topologies/{topology_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Topology */
        post: operations["validate_topology_api_v1_topologies__topology_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_json_api_v1_topologies_import_json_post */
        Body_import_json_api_v1_topologies_import_json_post: {
            /** File */
            file: string;
        };
        /** BuildRequest */
        BuildRequest: {
            /**
             * Fresh
             * @default false
             */
            fresh: boolean;
            /** Refs */
            refs: string[];
        };
        /**
         * BuildSource
         * @description Build the image from ``<source>/<context>/<dockerfile>``.
         */
        BuildSource: {
            /** Args */
            args?: {
                [key: string]: string;
            };
            /** Context */
            context: string;
            /**
             * Dockerfile
             * @default Dockerfile
             */
            dockerfile: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "build";
            /** Repo */
            repo: string;
        };
        /** Catalog */
        Catalog: {
            /** Categories */
            categories?: components["schemas"]["CategorySpec"][];
            /** Defaults */
            defaults: {
                [key: string]: string;
            };
            /**
             * Description
             * @default
             */
            description: string;
            /** Images */
            images?: {
                [key: string]: components["schemas"]["ImageSpec"];
            };
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["GitSource"] | components["schemas"]["PathSource"];
            };
            /** Types */
            types: {
                [key: string]: components["schemas"]["NodeTypeSpec"];
            };
            /** Version */
            version: number;
        };
        /** CategorySpec */
        CategorySpec: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** ContextOut */
        ContextOut: {
            /** Events */
            events: components["schemas"]["EventOut"][];
            /** Plan */
            plan: {
                [key: string]: unknown;
            };
            runtime: components["schemas"]["RuntimeOut"];
            topology: components["schemas"]["TopologyRecord"];
        };
        /** Diagnostic */
        Diagnostic: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Node Id */
            node_id?: string | null;
            /**
             * Path
             * @default
             */
            path: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning";
        };
        /** DiagnosticsSummary */
        DiagnosticsSummary: {
            /** Errors */
            errors: number;
            /** Warnings */
            warnings: number;
        };
        /** EventOut */
        EventOut: {
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: number;
            /** Job Id */
            job_id: string | null;
            /** Level */
            level: string;
            /** Message */
            message: string;
            /** Topology Id */
            topology_id: string | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Type */
            type: string;
        };
        /**
         * GitSource
         * @description A git repository the backend clones (and syncs on demand).
         */
        GitSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "git";
            /**
             * Ref
             * @default main
             */
            ref: string;
            /** Url */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Auth Required */
            auth_required: boolean;
            /** Engine */
            engine: string;
            /** Engine Detail */
            engine_detail: string;
            /** Engine Ok */
            engine_ok: boolean;
            /** Status */
            status: string;
            /** Topologies */
            topologies: number;
            /** Version */
            version: string;
        };
        /** HostBuildOut */
        HostBuildOut: {
            /** Can Build */
            can_build: boolean;
            /** Detail */
            detail: string;
            /** Platform */
            platform: string;
        };
        /** ImageSpec */
        ImageSpec: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Displayname */
            displayName: string;
            /** Platforms */
            platforms?: string[] | null;
            /** Source */
            source?: components["schemas"]["BuildSource"] | components["schemas"]["RegistrySource"];
            /**
             * Stability
             * @default stable
             * @enum {string}
             */
            stability: "stable" | "experimental" | "hidden";
        };
        /** ImageStatusOut */
        ImageStatusOut: {
            active_job?: components["schemas"]["JobOut"] | null;
            /** Built Fingerprint */
            built_fingerprint?: string | null;
            /** Built Revision */
            built_revision?: string | null;
            /** Created */
            created?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Display Name */
            display_name: string;
            /** Expected Fingerprint */
            expected_fingerprint?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "build" | "registry";
            last_job?: components["schemas"]["JobOut"] | null;
            /** Platforms */
            platforms?: string[] | null;
            /** Reason */
            reason: string;
            /** Ref */
            ref: string;
            /** Size */
            size?: number | null;
            /** Source */
            source?: string | null;
            /**
             * Stability
             * @enum {string}
             */
            stability: "stable" | "experimental" | "hidden";
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "missing" | "stale" | "unmanaged" | "unavailable" | "building" | "failed";
        };
        /** ImagesReport */
        ImagesReport: {
            host: components["schemas"]["HostBuildOut"];
            /** Images */
            images: components["schemas"]["ImageStatusOut"][];
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
        };
        /**
         * JobLogOut
         * @description A line-aligned slice of a job's log. Poll again from ``next_offset``.
         */
        JobLogOut: {
            /** Done */
            done: boolean;
            /** Next Offset */
            next_offset: number;
            /** Offset */
            offset: number;
            /** Size */
            size: number;
            /** Text */
            text: string;
        };
        /** JobOut */
        JobOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Steps */
            steps: components["schemas"]["JobStep"][];
            /** Subject */
            subject?: string | null;
            /** Topology Id */
            topology_id?: string | null;
        };
        /** JobStep */
        JobStep: {
            /** Ended At */
            ended_at?: string | null;
            /** Jobs */
            jobs?: string[];
            /** Message */
            message?: string | null;
            /** Name */
            name: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        };
        /** LabOut */
        LabOut: {
            /**
             * Classification
             * @enum {string}
             */
            classification: "tracked" | "orphan";
            /** Lab Hash */
            lab_hash: string;
            /** Machines */
            machines: string[];
            /** Running */
            running: number;
            /** Topology Id */
            topology_id?: string | null;
            /** Topology Name */
            topology_name?: string | null;
            /** Total */
            total: number;
            /** User Prefix */
            user_prefix: string;
        };
        /** LabsReport */
        LabsReport: {
            /** Labs */
            labs: components["schemas"]["LabOut"][];
            /** Stale */
            stale: components["schemas"]["StaleOut"][];
        };
        /** NodeState */
        NodeState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** State */
            state: string;
        };
        /** NodeTypeSpec */
        NodeTypeSpec: {
            /** Category */
            category: string;
            /** Color */
            color: string;
            /** Defaultimage */
            defaultImage: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Displayname */
            displayName: string;
            /** Icon */
            icon: string;
            /** Images */
            images?: string[];
            /** Label */
            label: string;
            /** Purduelevel */
            purdueLevel?: number | null;
            /**
             * Role
             * @enum {string}
             */
            role: "router" | "switch" | "host";
            /** Webuiport */
            webUiPort?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * PathSource
         * @description A directory on the backend's filesystem (e.g. a mounted checkout).
         */
        PathSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "path";
            /** Path */
            path: string;
        };
        /** PlanOut */
        PlanOut: {
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
            /** Plan */
            plan: {
                [key: string]: unknown;
            };
        };
        /** PresetList */
        PresetList: {
            /** Presets */
            presets: components["schemas"]["PresetSummary"][];
        };
        /** PresetSummary */
        PresetSummary: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Scenario Count
             * @default 0
             */
            scenario_count: number;
            /**
             * Site Count
             * @default 0
             */
            site_count: number;
        };
        /** PurgeResult */
        PurgeResult: {
            /** Lab Hash */
            lab_hash: string;
            /** Topology Id */
            topology_id?: string | null;
        };
        /** ReconcileResult */
        ReconcileResult: {
            /** Orphans */
            orphans: number;
            /** Reset */
            reset: number;
        };
        /**
         * RegistrySource
         * @description Pull the image by ref from a registry (the default).
         */
        RegistrySource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "registry";
        };
        /** RuntimeOut */
        RuntimeOut: {
            active_job?: components["schemas"]["JobOut"] | null;
            /** Nodes */
            nodes: components["schemas"]["NodeState"][];
            /** Status */
            status: string;
            /** Topology Id */
            topology_id: string;
            /** Version */
            version: number;
        };
        /** SourceOut */
        SourceOut: {
            active_job?: components["schemas"]["JobOut"] | null;
            /** Available */
            available: boolean;
            /** Can Sync */
            can_sync: boolean;
            /** Detail */
            detail: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "git" | "path";
            last_job?: components["schemas"]["JobOut"] | null;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Ref */
            ref?: string | null;
            /** Revision */
            revision?: string | null;
            /** Url */
            url?: string | null;
        };
        /** StaleOut */
        StaleOut: {
            /** Lab Hash */
            lab_hash: string;
            /** Topology Id */
            topology_id: string;
            /** Topology Name */
            topology_name: string;
        };
        /** TopologyCreate */
        TopologyCreate: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
        };
        /** TopologyRecord */
        TopologyRecord: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Diagnostics */
            diagnostics?: components["schemas"]["Diagnostic"][];
            /** Engine State */
            engine_state?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** TopologySummary */
        TopologySummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** TopologyUpdate */
        TopologyUpdate: {
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /** Name */
            name?: string | null;
            /** Version */
            version?: number | null;
        };
        /** ValidateBody */
        ValidateBody: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
            summary: components["schemas"]["DiagnosticsSummary"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_catalog_api_v1_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    list_images_api_v1_images_get: {
        parameters: {
            query?: {
                /** @description Only the images this topology's nodes use */
                topology_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagesReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_images_api_v1_images_builds_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_log_api_v1_jobs__job_id__log_get: {
        parameters: {
            query?: {
                /** @description Omit to read the tail */
                offset?: number | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_api_v1_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetList"];
                };
            };
        };
    };
    get_preset_api_v1_presets__preset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_preset_api_v1_presets__preset_id__load_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                preset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_source_api_v1_sources__name__sync_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    labs_api_v1_system_labs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabsReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_lab_api_v1_system_labs__lab_hash__purge_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                lab_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_reconcile_api_v1_system_reconcile_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconcileResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topologies_api_v1_topologies_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_topology_api_v1_topologies_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopologyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_json_api_v1_topologies_import_json_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_json_api_v1_topologies_import_json_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_data_api_v1_topologies_validate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topology_api_v1_topologies__topology_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                topology_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_topology_api_v1_topologies__topology_id__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                authorization?: string | null;
            };
            path: {
                topology_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopologyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_topology_api_v1_topologies__topology_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                topology_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_context_api_v1_topologies__topology_id__context_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                topology_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deploy_api_v1_topologies__topology_id__deploy_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                topology_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    destroy_api_v1_topologies__topology_id__destroy_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                topology_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_v1_topologies__topology_id__events_get: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                topology_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_topology_api_v1_topologies__topology_id__export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                topology_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topology_jobs_api_v1_topologies__topology_id__jobs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                topology_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_v1_topologies__topology_id__plan_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                topology_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runtime_api_v1_topologies__topology_id__runtime_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                topology_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_topology_api_v1_topologies__topology_id__validate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                topology_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
